# Generated by Django 3.0.6 on 2020-05-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=15)),
                ('car_model', models.CharField(max_length=15)),
                ('year_of_issue', models.IntegerField()),
                ('transmition', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Robot', 'Robot')], max_length=10)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Black', 'Black'), ('Withe', 'Withe'), ('Gray', 'Gray')], max_length=10)),
            ],
        ),
    ]
