# Generated by Django 3.0.6 on 2020-05-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='transmition',
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[(1, 'Manual'), (2, 'Automatic'), (3, 'Robot')], default=1),
        ),
    ]
