# Generated by Django 3.0.6 on 2020-05-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200518_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.AddField(
            model_name='car',
            name='transmition',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Robot', 'Robot')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
